import {
  Compass,
  FolderKanban,
  Heart,
  House,
  LifeBuoy,
  MessageSquare,
  Settings,
  Store,
  User,
  Users,
  type LucideIcon,
} from "lucide-react";
import type {
  AppSeedUser,
  AvatarPreset,
  CountryData,
  LocationData,
  NavItem,
  PlanKey,
  Question,
  SharedProject,
} from "@/types/prototype";

export const LOCATION_DATA: LocationData = {
  Africa: {
    Egypt: {
      regionLabel: "Governorate",
      cityLabel: "City",
      regions: [
        { name: "Cairo Governorate", cities: ["Cairo", "Heliopolis", "Nasr City"] },
        { name: "Alexandria Governorate", cities: ["Alexandria", "Borg El Arab"] },
      ],
    },
    Kenya: {
      regionLabel: "County",
      cityLabel: "City / Town",
      regions: [
        { name: "Nairobi County", cities: ["Nairobi", "Karen", "Westlands"] },
        { name: "Mombasa County", cities: ["Mombasa", "Likoni"] },
      ],
    },
  },
  Asia: {
    India: {
      regionLabel: "State",
      cityLabel: "City",
      regions: [
        { name: "Maharashtra", cities: ["Mumbai", "Pune"] },
        { name: "Karnataka", cities: ["Bengaluru", "Mysuru"] },
      ],
    },
    Israel: {
      regionLabel: "District",
      cityLabel: "City",
      regions: [
        { name: "Tel Aviv District", cities: ["Tel Aviv", "Herzliya"] },
        { name: "Jerusalem District", cities: ["Jerusalem"] },
        { name: "Northern District", cities: ["Haifa", "Nazareth"] },
      ],
    },
    Japan: {
      regionLabel: "Prefecture",
      cityLabel: "City",
      regions: [
        { name: "Tokyo", cities: ["Tokyo", "Shibuya", "Shinjuku"] },
        { name: "Osaka", cities: ["Osaka"] },
      ],
    },
  },
  Europe: {
    France: {
      regionLabel: "Region",
      cityLabel: "City",
      regions: [
        { name: "Île-de-France", cities: ["Paris"] },
        { name: "Provence-Alpes-Côte d'Azur", cities: ["Marseille", "Nice"] },
      ],
    },
    Portugal: {
      regionLabel: "District",
      cityLabel: "City",
      regions: [
        { name: "Lisbon District", cities: ["Lisbon", "Cascais"] },
        { name: "Porto District", cities: ["Porto"] },
      ],
    },
    "United Kingdom": {
      regionLabel: "Nation / Region",
      cityLabel: "City",
      regions: [
        { name: "England", cities: ["London", "Manchester"] },
        { name: "Scotland", cities: ["Edinburgh", "Glasgow"] },
      ],
    },
  },
  "North America": {
    Canada: {
      regionLabel: "Province",
      cityLabel: "City",
      regions: [
        { name: "Ontario", cities: ["Toronto", "Ottawa"] },
        { name: "British Columbia", cities: ["Vancouver", "Victoria"] },
      ],
    },
    Mexico: {
      regionLabel: "State",
      cityLabel: "City",
      regions: [
        { name: "Jalisco", cities: ["Guadalajara", "Puerto Vallarta"] },
        { name: "Nuevo León", cities: ["Monterrey"] },
      ],
    },
    "United States": {
      regionLabel: "State",
      cityLabel: "City",
      regions: [
        { name: "California", cities: ["San Diego", "Los Angeles", "San Francisco", "Joshua Tree"] },
        { name: "Texas", cities: ["Austin", "Dallas", "Houston"] },
        { name: "Florida", cities: ["Miami", "Orlando"] },
        { name: "Oregon", cities: ["Portland"] },
        { name: "Washington", cities: ["Seattle"] },
      ],
    },
  },
  Oceania: {
    Australia: {
      regionLabel: "State / Territory",
      cityLabel: "City",
      regions: [
        { name: "New South Wales", cities: ["Sydney"] },
        { name: "Victoria", cities: ["Melbourne"] },
      ],
    },
  },
  "South America": {
    Brazil: {
      regionLabel: "State",
      cityLabel: "City",
      regions: [
        { name: "São Paulo", cities: ["São Paulo"] },
        { name: "Rio de Janeiro", cities: ["Rio de Janeiro"] },
      ],
    },
    Chile: {
      regionLabel: "Region",
      cityLabel: "City",
      regions: [
        { name: "Santiago Metropolitan", cities: ["Santiago"] },
        { name: "Valparaíso", cities: ["Valparaíso"] },
      ],
    },
  },
};

export const PLAN_OPTIONS: {
  key: PlanKey;
  title: string;
  price: string;
  subtitle: string;
}[] = [
  {
    key: "starter",
    title: "Starter Plan",
    price: "$1",
    subtitle: "One-time starter access for prototype testing.",
  },
  {
    key: "pro",
    title: "Pro Plan",
    price: "$10/month",
    subtitle: "Monthly plan for advanced testing and premium collaboration flows.",
  },
  {
    key: "skip",
    title: "Skip for Now",
    price: "$0 now",
    subtitle: "Continue through the prototype without entering payment details.",
  },
];

export const AVATAR_PRESETS: AvatarPreset[] = [
  { id: "forest-guide", label: "Forest Guide", emoji: "🌿", gradient: "from-emerald-400 via-green-500 to-teal-600" },
  { id: "sun-builder", label: "Sun Builder", emoji: "☀️", gradient: "from-amber-300 via-orange-400 to-rose-500" },
  { id: "moon-maker", label: "Moon Maker", emoji: "🌙", gradient: "from-indigo-400 via-violet-500 to-fuchsia-500" },
  { id: "trail-scout", label: "Trail Scout", emoji: "🧭", gradient: "from-sky-400 via-cyan-500 to-blue-600" },
  { id: "harbor-heart", label: "Harbor Heart", emoji: "💙", gradient: "from-cyan-300 via-sky-500 to-indigo-500" },
  { id: "earth-keeper", label: "Earth Keeper", emoji: "🌎", gradient: "from-lime-400 via-green-600 to-emerald-700" },
];

export const sharedProjectsSeed: SharedProject[] = [
  {
    id: 1,
    title: "San Diego Family Garden Co-op",
    creatorId: "u-ava",
    creator: "Ava Chen",
    category: "Community Living",
    city: "San Diego",
    state: "California",
    country: "United States",
    continent: "North America",
    location: "San Diego, California, United States, North America",
    description:
      "A family-friendly garden and skills-sharing group focused on food growing, homeschooling meetups, and weekend build days.",
    tags: ["family", "gardening", "homeschool", "community"],
    neededSkillIds: ["food-production", "teaching-skill-sharing", "childcare-education", "governance"],
    desiredMemberTypes: ["Family mentors", "Garden coordinators", "Governance facilitators"],
    locationConstraints: "Best for members who can participate in Southern California weekend gatherings.",
    resourceNeeds: ["Garden tools", "Seed library", "Family education space"],
    fundingGoal: "$8,000",
    fundingUse: "Shared garden beds, irrigation setup, and child-friendly workshop materials.",
    fundingNeeds: ["Local sponsors", "Member contributions"],
    communityStyle: "Family-centered",
    profileKeywords: ["family", "garden", "homeschool", "community", "teaching", "kids"],
    thumbnail: "SD",
    lat: 32.7157,
    lng: -117.1611,
    privacy: "public",
    joinStatus: "not_joined",
  },
  {
    id: 2,
    title: "Joshua Tree Off-Grid Build Camp",
    creatorId: "u-marcus",
    creator: "Marcus Lee",
    category: "Off-Grid",
    city: "Joshua Tree",
    state: "California",
    country: "United States",
    continent: "North America",
    location: "Joshua Tree, California, United States, North America",
    description:
      "A hands-on off-grid project building solar-ready tiny structures, water systems, and a shared maker yard in the desert.",
    tags: ["off-grid", "solar", "building", "tiny home"],
    neededSkillIds: ["power-systems", "water-systems", "construction-repair", "project-planning", "emergency-preparedness"],
    desiredMemberTypes: ["Solar builders", "Water systems helpers", "Safety coordinators"],
    locationConstraints: "Desert build sprints require heat readiness and reliable transportation.",
    resourceNeeds: ["Solar kits", "Water storage tanks", "Shade structures", "Tool trailer"],
    fundingGoal: "$24,000",
    fundingUse: "Solar-ready structures, water storage, and shared workshop equipment.",
    fundingNeeds: ["Crowdfunding", "Equipment sponsors", "Builder contributions"],
    communityStyle: "Hands-on build crew",
    profileKeywords: ["off-grid", "solar", "build", "land", "construction", "independence"],
    thumbnail: "JT",
    lat: 34.1347,
    lng: -116.3131,
    privacy: "public",
    joinStatus: "not_joined",
  },
  {
    id: 3,
    title: "Portland Creative Homestead Circle",
    creatorId: "u-lina",
    creator: "Lina Patel",
    category: "Creative Community",
    city: "Portland",
    state: "Oregon",
    country: "United States",
    continent: "North America",
    location: "Portland, Oregon, United States, North America",
    description:
      "A small homestead network for artists, gardeners, and families who want shared meals, workshops, and creative studio days.",
    tags: ["art", "homestead", "families", "workshops"],
    neededSkillIds: ["community-culture-building", "food-production", "teaching-skill-sharing", "resource-sharing"],
    desiredMemberTypes: ["Artists", "Workshop hosts", "Shared meal coordinators"],
    locationConstraints: "Designed for Portland-area members and occasional visiting collaborators.",
    resourceNeeds: ["Shared studio supplies", "Workshop facilitators", "Composting setup"],
    fundingGoal: "$6,500",
    fundingUse: "Workshop materials, studio equipment, and shared meal infrastructure.",
    fundingNeeds: ["Workshop fees", "Material donations"],
    communityStyle: "Education and skill-sharing",
    profileKeywords: ["creative", "art", "music", "homestead", "community", "family"],
    thumbnail: "PC",
    lat: 45.5152,
    lng: -122.6784,
    privacy: "private",
    joinStatus: "not_joined",
  },
  {
    id: 4,
    title: "Austin Remote Work + Build Collective",
    creatorId: "u-daniel",
    creator: "Daniel Ross",
    category: "Hybrid Living",
    city: "Austin",
    state: "Texas",
    country: "United States",
    continent: "North America",
    location: "Austin, Texas, United States, North America",
    description:
      "A community for people balancing remote work with intentional living, weekend building projects, and shared land planning.",
    tags: ["remote work", "building", "land", "planning"],
    neededSkillIds: ["project-planning", "construction-repair", "administration-documentation", "financial-management"],
    desiredMemberTypes: ["Remote workers", "Project planners", "Budget-minded builders"],
    locationConstraints: "Members can contribute remotely, with optional Austin build weekends.",
    resourceNeeds: ["Planning templates", "Tool sharing system", "Remote work infrastructure"],
    fundingGoal: "$12,000",
    fundingUse: "Site planning, workshop setup, and shared admin systems.",
    fundingNeeds: ["Member dues", "Tool library sponsors"],
    communityStyle: "Remote-work friendly",
    profileKeywords: ["remote", "operations", "tech", "building", "planning", "community"],
    thumbnail: "AT",
    lat: 30.2672,
    lng: -97.7431,
    privacy: "public",
    joinStatus: "not_joined",
  },
  {
    id: 5,
    title: "Toronto Learning Exchange Village",
    creatorId: "u-sofia",
    creator: "Sofia Alvarez",
    category: "Education",
    city: "Toronto",
    state: "Ontario",
    country: "Canada",
    continent: "North America",
    location: "Toronto, Ontario, Canada, North America",
    description:
      "A learning-focused village for families who want shared education, outdoor routines, and practical skills workshops.",
    tags: ["education", "family", "learning", "village"],
    neededSkillIds: ["childcare-education", "teaching-skill-sharing", "governance", "food-production"],
    desiredMemberTypes: ["Parents", "Educators", "Outdoor learning facilitators"],
    locationConstraints: "Strongest fit for families near Toronto who want recurring in-person learning days.",
    resourceNeeds: ["Outdoor classroom supplies", "Parent facilitator network", "Garden curriculum"],
    fundingGoal: "$9,000",
    fundingUse: "Learning space setup, outdoor supplies, and curriculum workshops.",
    fundingNeeds: ["Education grants", "Parent contributions"],
    communityStyle: "Education and skill-sharing",
    profileKeywords: ["education", "family", "village", "nature", "teaching", "kids"],
    thumbnail: "TO",
    lat: 43.6532,
    lng: -79.3832,
    privacy: "private",
    joinStatus: "not_joined",
  },
  {
    id: 6,
    title: "Northern California Regenerative Farm Hub",
    creatorId: "u-priya",
    creator: "Priya Singh",
    category: "Regenerative Farming",
    city: "San Francisco",
    state: "California",
    country: "United States",
    continent: "North America",
    location: "San Francisco, California, United States, North America",
    description:
      "A regenerative farm startup looking for growers, builders, and families interested in long-term community life on shared land.",
    tags: ["farming", "regenerative", "land", "families"],
    neededSkillIds: ["food-production", "land-management", "construction-repair", "water-systems", "financial-management"],
    desiredMemberTypes: ["Growers", "Land stewards", "Budget leads", "Builders"],
    locationConstraints: "Long-term members should be open to Northern California land-based rhythms.",
    resourceNeeds: ["Soil amendments", "Irrigation planning", "Propagation supplies", "Budget support"],
    fundingGoal: "$30,000",
    fundingUse: "Food production setup, water systems, and early-stage farm infrastructure.",
    fundingNeeds: ["Farm grants", "Member investment", "Infrastructure sponsors"],
    communityStyle: "Regenerative land stewardship",
    profileKeywords: ["farm", "land", "family", "off-grid", "growing", "healing"],
    thumbnail: "NC",
    lat: 37.7749,
    lng: -122.4194,
    privacy: "public",
    joinStatus: "not_joined",
  },
  {
    id: 7,
    title: "Monterrey Maker Homestead",
    creatorId: "u-carlos",
    creator: "Carlos Medina",
    category: "Creative Community",
    city: "Monterrey",
    state: "Nuevo León",
    country: "Mexico",
    continent: "North America",
    location: "Monterrey, Nuevo León, Mexico, North America",
    description:
      "A bilingual maker and family homestead network blending design, food growing, workshops, and shared tools.",
    tags: ["maker", "family", "bilingual", "community"],
    neededSkillIds: ["construction-repair", "teaching-skill-sharing", "food-production", "resource-sharing", "communication"],
    desiredMemberTypes: ["Bilingual makers", "Tool stewards", "Family workshop hosts"],
    locationConstraints: "Best for bilingual members near Monterrey or traveling for maker weekends.",
    resourceNeeds: ["Shared tools", "Bilingual workshop materials", "Maker space storage"],
    fundingGoal: "$11,000",
    fundingUse: "Maker equipment, tool library setup, and bilingual workshop programming.",
    fundingNeeds: ["Tool donations", "Workshop revenue"],
    communityStyle: "Education and skill-sharing",
    profileKeywords: ["creative", "family", "community", "making", "building", "teaching"],
    thumbnail: "MX",
    lat: 25.6866,
    lng: -100.3161,
    privacy: "public",
    joinStatus: "not_joined",
  },
  {
    id: 8,
    title: "Miami Wellness + Community Harbor",
    creatorId: "u-jasmine",
    creator: "Jasmine Cole",
    category: "Hybrid Living",
    city: "Miami",
    state: "Florida",
    country: "United States",
    continent: "North America",
    location: "Miami, Florida, United States, North America",
    description:
      "A warm-climate project for remote workers, wellness practitioners, and families seeking a flexible shared lifestyle.",
    tags: ["wellness", "remote", "family", "warm climate"],
    neededSkillIds: ["health-wellness", "community-culture-building", "emergency-preparedness", "administration-documentation"],
    desiredMemberTypes: ["Wellness practitioners", "Remote workers", "Emergency planners"],
    locationConstraints: "Flexible warm-climate participation with seasonal in-person gatherings.",
    resourceNeeds: ["Wellness facilitators", "Emergency plan templates", "Flexible shared space"],
    fundingGoal: "$7,500",
    fundingUse: "Wellness programming, emergency readiness kits, and shared space setup.",
    fundingNeeds: ["Program sponsors", "Member contributions"],
    communityStyle: "Balanced mix",
    profileKeywords: ["wellness", "remote", "family", "care", "community", "work"],
    thumbnail: "MI",
    lat: 25.7617,
    lng: -80.1918,
    privacy: "public",
    joinStatus: "not_joined",
  },
];

export const myProjectCategories = [
  "Community Living",
  "Off-Grid",
  "Creative Community",
  "Hybrid Living",
  "Education",
  "Regenerative Farming",
  "General",
] as const;

export const navItems: NavItem[] = [
  { key: "home", label: "Home", icon: House },
  { key: "matches", label: "Matches", icon: Users },
  { key: "favorites", label: "Favorites", icon: Heart },
  { key: "projects", label: "Projects", icon: FolderKanban },
  { key: "chats", label: "Chats", icon: MessageSquare },
  { key: "support", label: "Support", icon: LifeBuoy },
  { key: "ecosystem", label: "Ecosystem", icon: Store },
  { key: "settings", label: "Settings", icon: Settings },
  { key: "account_info", label: "Account", icon: User },
  { key: "answers_summary", label: "Answers", icon: Compass },
];

export const categoryOrder = [
  "Status",
  "Location + Timing",
  "Project Preferences",
  "Lifestyle",
  "Work + Finances",
  "Skills + Abilities",
  "Commitment + Fit",
] as const;

export const seedUsers: AppSeedUser[] = [
  { id: "u-ava", fullName: "Ava Chen", avatarLabel: "AC", avatarGradient: "from-emerald-400 to-teal-600", online: true },
  { id: "u-marcus", fullName: "Marcus Lee", avatarLabel: "ML", avatarGradient: "from-orange-400 to-rose-600", online: false },
  { id: "u-lina", fullName: "Lina Patel", avatarLabel: "LP", avatarGradient: "from-violet-400 to-fuchsia-600", online: true },
  { id: "u-daniel", fullName: "Daniel Ross", avatarLabel: "DR", avatarGradient: "from-sky-400 to-blue-600", online: true },
  { id: "u-sofia", fullName: "Sofia Alvarez", avatarLabel: "SA", avatarGradient: "from-pink-400 to-rose-600", online: false },
  { id: "u-priya", fullName: "Priya Singh", avatarLabel: "PS", avatarGradient: "from-lime-400 to-green-700", online: true },
  { id: "u-carlos", fullName: "Carlos Medina", avatarLabel: "CM", avatarGradient: "from-cyan-400 to-indigo-600", online: false },
  { id: "u-jasmine", fullName: "Jasmine Cole", avatarLabel: "JC", avatarGradient: "from-amber-400 to-orange-600", online: true },
];

export const SAMPLE_COUNTRY = (continent: string, country: string): CountryData | null => {
  return LOCATION_DATA[continent]?.[country] ?? null;
};
